📝 Added Code Acedemy links in various lists
donutboy929/hapebeast-coding-cave-resources pull request #7
Opened 2022-01-06 16:06 UTC by Rid

Added links to various lists to the Code Academy catalogue for each language.

Signed-off-by: Rid <rid@cylo.io>

2022-01-06 16:17 UTC, donutboy929 requested changes
Shorten descriptions to be more concise please :), I'll update CONTRIBUTING.md to reflect the formatting.

2022-01-06 16:17 UTC, donutboy929 commented on README.md
> +- [Code Academy, free Python courses](https://www.codecademy.com/catalog/language/python) - This course is a great introduction to both fundamental programming concepts and the Python programming lan
Could you shorten the descriptions? Remove unnecessary things like "This course is..." and "You will learn...".

This one could be something like: Introduction to the fundamental programming concepts of Python.

2022-01-06 16:20 UTC, Rid commented on README.md
> +- [Code Academy, free Python courses](https://www.codecademy.com/catalog/language/python) - This course is a great introduction to both fundamental programming concepts and the Python programming lan
NP, Just this one, or all of them?

2022-01-06 16:36 UTC, donutboy929 commented on README.md
> +- [Code Academy, free Python courses](https://www.codecademy.com/catalog/language/python) - This course is a great introduction to both fundamental programming concepts and the Python programming lan
All of them please

2022-01-07 15:31 UTC, donutboy929 approved these changes

2022-01-07 15:33 UTC, donutboy929 approved these changes

2022-01-07 15:34 UTC, merged